rescript-lang/syntax

src/napkin_core.ml, src/napkin_grammar.ml, src/napkin_parser.ml, src/napkin_printer.ml, src/napkin_scanner.ml, src/napkin_token.ml, tests/parsing/grammar/pattern/polyvariants.js, tests/parsing/grammar/pattern/variants.js, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/polyvariant.js, tests/printer/pattern/__snapshots__/render.spec.js.snap, tests/printer/pattern/type.ns, tests/printer/pattern/variant.ns
=> Change poly variant `##` spread to `#...`

src/napkin_core.ml, src/napkin_parsetree_viewer.ml, src/napkin_parsetree_viewer.mli, src/napkin_printer.ml, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/if.js, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/if.js
`if let` brings pattern matching to `if`
---------------------------------------
`if let PAT = EXPR { BODY }`
The motivation for having any construct at all for this is to simplify the cases that today call for
a switch statement with a single non-trivial case. This is predominately used for unwrapping
`option<'t>` values, but can be used elsewhere.
Before:
```reason
switch(optVal) {
| Some(x) => doSomethingWith(x)
| _ => ()
}
```
After:
```reason
if let Some(x) = optVal {
doSomethingWith(x)
}
```
Complex example:
```reason
if let Some(x) = optVal when x > 10 {
doSomethingWith(x)
} else if let Theme({color: Red | Blue, emoji}) = getTheme() {
doSomething()
} else {
doSomethingElse()
}
```
There are >500 occurrences in FB of `| _ => ()` where this form would be more appropriate
This is …
=> Add `if let` syntax

src/napkin_core.ml, tests/parsing/errors/structure/__snapshots__/parse.spec.js.snap, tests/parsing/errors/structure/gh16A.ns, tests/parsing/errors/structure/gh16B.ns
Fixes https://github.com/BuckleScript/syntax/issues/16
=> Close binary expressions parsing correct

src/napkin_ast_conversion.ml, src/napkin_core.ml, src/napkin_printer.ml, tests/parsing/errors/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/errors/structure/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/infiniteLoops/__snapshots__/parse.spec.js.snap, tests/parsing/recovery/string/__snapshots__/parse.spec.js.snap
By parsing \`foo bar\` as `{js|foo|js}`, we get unicode for free in the javascript output.
For future conversion,`{||}` will be converted in `{js||js}` once upfront.
Fixes https://github.com/BuckleScript/syntax/issues/13
=> Default parsing of template literals to preserve unicode.

src/napkin_core.ml, src/napkin_token.ml, tests/parsing/errors/expressions/__snapshots__/parse.spec.js.snap, tests/printer/comments/__snapshots__/render.spec.js.snap, tests/printer/comments/blockExpr.res
Fixes https://github.com/BuckleScript/syntax/issues/28
=> Make `catch` not a keyword, but just an identifier.

src/napkin_diagnostics.mli
Exposes the Diagnostic `toString` and `explain` function as public API.
1) The playground needs a way to transform a single `Diagnostic.t` into a pretty report string (right now I can only stringify a list of `Diagnostic.t` with `stringOfReport`)
2) The playground needs a small msg string for hover message display (basically only the thing `explain` returns)
=> Expose Napkin_diagnostic's toString and explain function

.depend, Makefile, src/napkin_io.ml, src/napkin_io.mli, src/napkin_multi_printer.ml
Opening a temp file of the same name is gonna get into race conditions.
For conversion, some things might be running in parallel.
No temp file race. It's not even certain that the file will be written
to before we read it back. You don't want these issues to creep up
sometime during conversion and being undebuggable.
=> Prevent race conditions in Reason -> Res printing.

.depend, src/napkin_io.ml, src/napkin_io.mli, src/napkin_multi_printer.ml, src/napkin_outcome_printer.ml, tests/napkin_test.ml, tests/oprint/oprint.res, tests/oprint/oprint.res.snapshot, tests/oprint/test.res
Workflow:
1) Add code in `tests/oprint/oprint.res`
2) Run tests through `make test`
3) (optional) update snapshots through `./lib/test.exe -update-snapshot`
How it works:
- `tests/oprint/oprint.res` will be read into memory and typechecked.
- The inferred signature (i.e. the type of the module `oprint.res`) will then be converted to the outcome tree.
- The outcome tree is printed to a string and stored in a snapshot `tests/oprint/oprint.res.snapshot`
=> Infrastructure for outcome printer tests

src/napkin_core.ml
The location should start from the attributes.
e.g.
```swift
@bs.module("BootloaderResource") external read: JSResource.t<'a> => 'a = "read"
```
the location should start from `@` not from `e` of `external`.
=> Fix location for external declaration with attributes.

src/napkin_core.ml, src/napkin_diagnostics.ml, src/napkin_printer.ml, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typeDef/typeParams.js, tests/parsing/errors/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typexpr/typeVar.res, tests/parsing/grammar/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/typexpr/var.js, tests/printer/typeDef/__snapshots__/render.spec.js.snap, tests/printer/typeDef/exoticIdent.js, tests/printer/typeDef/typeParams.js, tests/printer/typexpr/__snapshots__/render.spec.js.snap, tests/printer/typexpr/var.js
Allow uppercase identifiers in type params and typexpr variables
```typescript
type x<'A> = 'A
```
Fixes https://github.com/BuckleScript/syntax/issues/49
=> Uppercase Generics

tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/uncurrried.re
Unfortunately there's a bug in the Reason parser.
`f(. a)` will parse the `@bs` attribute in the wrong place, when it's an expression at the module level: https://github.com/facebook/reason/issues/2565
The new Res syntax has the correct behaviour. Unfortunately we can't
fix bugs from Reason, we would change the semantics of the program.
=> Document uncurried conversion through test cases.

src/napkin_core.ml, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typexpr/garbage.res
Report errors when encountering unexpected tokens in atomic type expressions. Previously errors just weren't logged at all.
Fixes https://github.com/BuckleScript/syntax/issues/48
=> Report errors when parsing type expressions.

.depend, src/napkin_parser.ml, src/napkin_parser.mli, src/napkin_reason_binary_driver.ml, src/napkin_scanner.ml, src/napkin_scanner.mli, tests/napkin_test.ml
Instead of exposing a surface syntax to change the line number of the scanner at parse time, we can expose a programmatic api for power users to seed the line number
```ocaml
let parser = Napkin_parser.make ~line:2 mySourceCode myFilename
```
=> Expose API to seed the initial line number of the parser.

src/napkin_driver.ml, src/napkin_multi_printer.ml
Exit parser instead of raising error
See #68. The problem we have is the 2nd and 3rd screenshots, with a superfluous and nonexistent location reported.
This happens because BS/OCaml's way of reporting an error is to catch e.g. a `Location.Error` exception. The reporting displays the location, then move on. This is problematic for our syntax, because we report more than one error (i.e. we have more than one location to show).
The theoretical solution is to refactor the BS/OCaml reporting pipeline to accept a new exception that allows more than one error. But this shakes things up too much, so our temporary solution is to print all the errors on the syntax side, then simply exit the process. No exception raised means the BS side also doesn't catch anything and tries to display that …
=> Exit parser instead of raising error

src/napkin_diagnostics.ml, src/napkin_diagnostics_printing_utils.ml, tests/parsing/errors/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/errors/other/__snapshots__/parse.spec.js.snap, tests/parsing/errors/pattern/__snapshots__/parse.spec.js.snap, tests/parsing/errors/scanner/__snapshots__/parse.spec.js.snap, tests/parsing/errors/signature/__snapshots__/parse.spec.js.snap, tests/parsing/errors/structure/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/infiniteLoops/__snapshots__/parse.spec.js.snap
2 newlines turn into 1 inside bsb. Not sure why. Format is temporary, so
this'll do until we remove it completely.
=> 2 newlines at the end of terminal report for now

.github/workflows/ci.yml, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/uncurrried.re
It provides stronger tests:
- Napkin is bootstrapped
- Equality check between the Parsetree from different parsers
- prints napkin code twice to check for inconsistencies.
=> Enable roundtrip-tests on ci

src/napkin_core.ml, src/napkin_parser.ml, src/napkin_parser.mli, src/napkin_scanner.ml, src/napkin_scanner.mli, src/napkin_token.ml, tests/parsing/recovery/string/__snapshots__/parse.spec.js.snap
The previous approach put the scanner in "Template" mode when the parser
was going to parse template literals. This resulted in some very awkward
code; upon scanning a token there was logic checking whether we were
in "Template" mode. Every non-template literal token would pay for this
extra branch…
The new parsing strategy works differently: when the parser needs to
parse template literals, it just asks the scanner immediately for a
template literal token. This is both more performant and easier to reason
about. Template literals are a different language, it makes sense to
split this into a separate scanning function.
Benchmark results: (lower is better)
=> Refactor parsing of string template literals.

src/napkin_core.ml, src/napkin_printer.ml, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/polyvariant.js, tests/parsing/grammar/pattern/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/pattern/polyvariants.js, tests/parsing/grammar/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/typexpr/polyVariant.res, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/pattern/__snapshots__/render.spec.js.snap, tests/printer/typexpr/__snapshots__/render.spec.js.snap
Implements https://github.com/BuckleScript/syntax/issues/76
The syntax for exotic identifiers in poly-variants is quite heavy: `#\"ease-in"`.
By extending the syntax for poly-variants with the following, we get a lighter weight version that is more pleasant to read and write:
```
poly-var ::=
HASH STRING
```
Example:
```ocaml
type animation = [ #"ease-in" | #"ease-out" ]
```
=> Light weight exotic poly variant syntax

src/res_core.ml, tests/parsing/errors/other/__snapshots__/parse.spec.js.snap, tests/parsing/errors/other/regionMissingComma.res, tests/printer/comments/modExpr.res, tests/printer/expr/exoticIdent.js, tests/printer/ffi/import.res
When a comma is missing between nodes in a region and the current token looks like the start of something valid in the current region, we should report an error with regards to the missing comma.
Example:
```reason
type student<'extraInfo> = {
name: string,
age: int                     // <-------- comma is missing
otherInfo: 'extraInfo
}
```
There is a missing comma between `int` and `otherInfo`.
`otherInfo` looks like a valid start of the record declaration.
We report the error here of the missing comma and then continue parsing the region.
Fixes https://github.com/rescript-lang/syntax/issues/100
=> Report error when comma is missing in comma delimited regions.

src/res_printer.ml, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/printer/comments/__snapshots__/render.spec.js.snap
Use case:
```
// {
//   let x = 1
// }
```
`//  <--whitespace-->          let x = 1` should not reformat to `// let x = 1`
Fixes https://github.com/rescript-lang/syntax/issues/109
=> Preserve user written leading white space in single line comments

src/res_core.ml, src/res_grammar.ml, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typeDef/inlineRecord.res
Fixes https://github.com/rescript-lang/syntax/issues/97
=> Give good error when a type declaration has an inline record type when not permitted

src/res_core.ml, tests/parsing/errors/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/errors/expressions/jsx.js, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/jsx.js, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/jsx.js
Found in #124.
Reason parser used to parse JSX elements like `<Foo.bar />`:
https://astexplorer.net/#/gist/e21abaf96358b68be3ed3da19930be58/32e083720817c639502960b54984dff8396a3f7b.
React ppx also builds on top of this to allow custom `make` names, e.g.
```reason
let t = <Foo.bar />
let t = <Foo.Bar />
```
is transformed into:
```reason
let t = React.createElement(Foo.bar, Foo.barProps()); /* We can call `bar` instead of `make` */
let t = React.createElement(Foo.Bar.make, Foo.Bar.makeProps());
```
(shameless plug, can be tested in https://jchavarri.github.io/ppx-explorer/ 😜 )
=> Parse <Foo.bar /> elements

src/res_cli.ml, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/polyvariant.js, tests/runner.js
Extracted from #124.
- Makes parser cli return exit code 1 if parsed result is invalid (except when `-recover` is passed)
- Adapt runner to check status after calling `rescript.exe`, fail test if status > 0
- Update test `parsing/grammar/expressions/polyvariant.js ` that was failing to parse
=> Update parser + test runner to fail when in non-recover mode

src/res_core.ml, src/res_diagnostics.ml, tests/parsing/errors/signature/__snapshots__/parse.spec.js.snap, tests/parsing/errors/signature/attributes.resi, tests/parsing/errors/structure/__snapshots__/parse.spec.js.snap, tests/parsing/errors/structure/attributes.res, tests/parsing/recovery/expression/__snapshots__/parse.spec.js.snap
Fixes https://github.com/rescript-lang/syntax/issues/141
=> Parse error when a non-standalone attribute is used standalone.

src/res_core.ml, src/res_diagnostics.ml, src/res_grammar.ml, tests/parsing/errors/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typeDef/typeDef.js
```
type Foo.bar = string
```
Proposed error message:
```
A type declaration's name cannot contain a module access path. Did you mean \`bar\`?
```
=> Add error message when type definition name contains a module access path

src/res_printer.ml, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/printer/other/__snapshots__/render.spec.js.snap, tests/printer/other/case.js
If you look at the `B | C | D` patterns in the following examples:
```
switch a {
| B
| C
| D => 1
| E => 2
}
switch a {
| B | C | D => 1
| E => 2
}
```
they have two different layouts:
* In the first example the user wrote them over multiple lines.
* The second has them on one line.
This commit implements a new strategy to print these two examples.
We now look at the style of the author: did he write it over multiple lines or not?
* If it is on one line, keep it on one line (unless it breaks the column width).
* If it is written over multiple lines, force break it over multiple lines.
This is also consistent with how we print variant declaration.
=> Implement intelligent breaking for chained or-patterns.

src/res_doc.ml, src/res_printer.ml, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/callback.js, tests/printer/other/__snapshots__/render.spec.js.snap
Fixes https://github.com/rescript-lang/syntax/issues/190
```rescript
// before
let make = fn((~a: option<string>=?, ~b: option<string>=?, ~c: option<string>=?, ~d: option<
string,
>=?, ~e: option<string>=?, x) => {
()
})
// after
let make = fn((
~a: option<string>=?,
~b: option<string>=?,
~c: option<string>=?,
~d: option<string>=?,
~e: option<string>=?,
x,
) => {
Js.log()
})
```
=> Tweak printing of callbacks to break correctly in case of annotated labeled arguments

src/res_scanner.ml, tests/idempotency/ocaml/stdlib/nativeint.ml, tests/idempotency/ocaml/typing/oprint.ml, tests/idempotency/ocaml/typing/parmatch.ml, tests/parsing/errors/scanner/__snapshots__/parse.spec.js.snap, tests/parsing/errors/scanner/nativeint.res, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/constants.js, tests/printer/other/__snapshots__/render.spec.js.snap, tests/printer/other/number.js
Fixes https://github.com/rescript-lang/syntax/issues/207
Nativeint has been removed in the compiler and does not make sense for a js backend.
cc @bobzhang
=> Remove support for nativeint

src/res_outcome_printer.ml, tests/oprint/oprint.res, tests/oprint/oprint.res.snapshot
This is relevant for editor tooling where types are displayed on hover:
**before**
```rescript
Js.Fn.arity2<(int, int) => int>
```
**after**
```rescript
(. int, int) => int
```
=> Implement pretty outcome printing for uncurried outcometree types

src/res_ast_conversion.ml, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/uncurrried.re, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/binary.js, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/binary.js
Fixes https://github.com/rescript-lang/syntax/issues/218
The following code should convert to ReScript correctly:
```rescript
let _ =
library.getBalance(. account)
->Promise.Js.catch(_ => Promise.resolved(None))
```
=> Convert Reason fast pipe with uncurried functions in the lhs to ReScript correct

CHANGELOG.md, src/res_driver_reason_binary.ml, src/res_scanner.ml, src/res_scanner.mli, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/string.re, tests/printer/other/__snapshots__/render.spec.js.snap, tests/printer/other/ocamlString.ml
Fixes https://github.com/rescript-lang/syntax/issues/237
The conversion from Reason to ReScript naively picks up `//` as comments inside quoted strings..
input:
```reason
let x = {j|https://www.apple.com|j};
let x = {|https://www.apple.com|};
let x = {js|https://www.apple.com|js};
```
output:
```rescript
let x = j`https://www.apple.com` //www.apple.com|j};
let x = `https://www.apple.com` //www.apple.com|};
let x = `https://www.apple.com` //www.apple.com|js};
```
This patch fixes this behaviour and doesn't produce any extra comments
=> Improve conversion of quoted strings from Reason.

CHANGELOG.md, src/res_printer.ml, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/jsx.js
Fixes https://github.com/rescript-lang/syntax/issues/231.
The comment would either not be printed or the indentation would be weird:
**before**
```Rescript
<Component amount={amount->BN.div(BN.new_("86400"))->BN.toString} />
<Component>
{// test
amount->BN.div(BN.new_("86400"))->BN.toString}
</Component>
```
**after**
```Rescript
<Component
amount={
// test
amount->BN.div(BN.new_("86400"))->BN.toString
}
/>
<Component>
{
// test
amount->BN.div(BN.new_("86400"))->BN.toString
}
</Component>
```
=> Improve printing of jsx children and props with leading line comment

CHANGELOG.md, src/res_printer.ml, tests/printer/comments/__snapshots__/render.spec.js.snap, tests/printer/comments/binaryExpr.res
Correctly print trailing below the lhs of a `Pexp_apply` with fast pipe or slow pipe.
Fixes https://github.com/rescript-lang/syntax/issues/234
**input**
```
promise
// comment
->Js.Promise.then(payload => {
Js.Promise.resolve(""->Obj.magic);
})
```
**before**
```
promise
->Js.Promise.then(payload => {
// comment
Js.Promise.resolve(""->Obj.magic);
})
```
**after**
```
promise
// comment
->Js.Promise.then(payload => {
Js.Promise.resolve(""->Obj.magic);
})
```
=> Fix printing of trailing comments under lhs of "pipe" expression.

CHANGELOG.md, src/res_printer.ml, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/bsObj.js, tests/printer/expr/record.js
Constrained expressions would not contain parens, and result into an invalid parse after printing.
**input**
```rescript
{"name": (name: string)}
```
**before**
```rescript
{"name": name: string} // invalid syntax
```
**after**
```rescript
{"name": (name: string)}
```
=> Fix printing of constrained expr rhs js object.

CHANGELOG.md, src/res_printer.ml, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/callback.js
Fix https://github.com/rescript-lang/syntax/issues/212
Sometimes one of the non-callback arguments will break in a function application where the first or last argument is a callback. There might be a single line comment in there, or a multiline string. We want to break all the arguments in this case for readability.
**before**
```rescript
showDialog(
`
Do you really want to leave this workspace?
Some more text with detailed explanations...
`, danger=true, ~confirmText="Yes, I am sure!", ~onConfirm={() => ()},
)
```
**after**
```rescript
showDialog(
`
Do you really want to leave this workspace?
Some more text with detailed explanations...
`,
~danger=true,
~confirmText="Yes, I am sure!",
~onConfirm={() => ()},
)
```
=> Improve printing of non-callback arguments in Pexp_apply with callbacks

CHANGELOG.md, src/res_parsetree_viewer.ml, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/let.js
Fix https://github.com/rescript-lang/syntax/issues/242
**before**
```rescript
let b = x
->Js.Dict.get("wm-property")
->Option.flatMap(Js.Json.decodeString)
->Option.flatMap(x =>
switch x {
| "like-of" => Some(#like)
| "repost-of" => Some(#repost)
| _ => None
}
)
```
**after**
```rescript
let b =
x
->Js.Dict.get("wm-property")
->Option.flatMap(Js.Json.decodeString)
->Option.flatMap(x =>
switch x {
| "like-of" => Some(#like)
| "repost-of" => Some(#repost)
| _ => None
}
)
```
=> improve indentation of fast pipe chain in let binding

CHANGELOG.md, src/res_printer.ml, tests/printer/typexpr/__snapshots__/render.spec.js.snap, tests/printer/typexpr/variant.js
Fixes https://github.com/rescript-lang/syntax/issues/245
Given:
```rescript
type currencyPoly = [#USD
| #CAD | #EUR]
type currencyPoly = [#USD | #CAD | #EUR]
```
we have two different layouts:
In the first example the user wrote them over multiple lines.
The second has them on one line.
This commit implements a new strategy to print these two examples.
We now look at the style of the author: did he write it over multiple lines or not?
If it is on one line, keep it on one line (unless it breaks the column width).
If it is written over multiple lines, force break it over multiple lines.
This is also consistent with how we print variant declaration.
=> Implement intelligent breaking for poly-var type expressions

CHANGELOG.md, src/res_core.ml, src/res_printer.ml, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/switch.js, tests/printer/comments/__snapshots__/render.spec.js.snap, tests/printer/other/__snapshots__/render.spec.js.snap
Pattern match cases can accept guards to further refine the criteria for matching a case. Pattern guards appear after the pattern and consist of an expression following the `when` keyword. The grammar expresses this as `| PATTERN => EXPRESSION when EXPRESSION`. An example:
```rescript
switch person1 {
| Teacher(_) => () // do nothing
| Student({reportCard: {gpa}}) when gpa < 0.5 =>
Js.log("What's happening")
| Student(_) =>
// fall-through, catch-all case
Js.log("Heyo")
}
```
We inherited the `when` keyword from our ancestors Reason and Ocaml. This keyword is not ideal:
1) It is not a keyword in JavaScript; you need to escape it in interop scenarios.
2) `when` takes up a keyword and is only being used in one small part of the grammar. (Cost/benefit)
3) Some people have trouble remembering …
=> Move towards "if" keyword for guards on pattern match cases.

CHANGELOG.md, src/res_core.ml, tests/idempotency/bs-css/Css.re, tests/idempotency/bs-css/CssEmotion.re, tests/idempotency/bs-css/CssEmotionJs.re, tests/idempotency/bs-css/CssJs.re, tests/idempotency/bs-css/Css_AtomicTypes.re, tests/idempotency/bs-css/Css_AtomicTypes.rei, tests/idempotency/bs-css/Css_Colors.re, tests/idempotency/bs-css/Css_Core.re, tests/idempotency/bs-css/Css_Js_Core.re, tests/idempotency/bs-css/Css_Js_Core.rei, tests/idempotency/bs-css/Css_Legacy_Core.re, tests/idempotency/bs-css/Css_Legacy_Core.rei, tests/idempotency/bs-css/Css_test.re, tests/idempotency/bs-css/Selectors_test.re, tests/idempotency/bs-css/Svg_test.re, tests/idempotency/bs-css/Test.re, tests/idempotency/bs-css/TestEmotion.re, tests/idempotency/bs-css/parse.spec.js, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typeDef/polyvariant.js, tests/parsing/grammar/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/typexpr/polyVariant.res, tests/printer/typexpr/__snapshots__/render.spec.js.snap, tests/printer/typexpr/variant.js
Fixes https://github.com/rescript-lang/syntax/issues/253
`[s]` or `[ListStyleType.t]` polyvariants should parse without more tag-spec's
=> Fix parsing of poly-var typexpr consisting of one tag-spec-first

CHANGELOG.md, src/res_core.ml, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/firstClassModule.js, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/firstClassModule.js
Fixes https://github.com/rescript-lang/syntax/issues/251
=> Fix parsing of first class module exprs as part of binary/ternary expr

src/res_comment.ml, src/res_driver.ml, src/res_driver_reason_binary.ml, src/res_io.ml, src/res_parser.ml, src/res_scanner.ml, src/res_scanner.mli
Profiler showed that bytes allocation costed a bit. We don't mutate the src, so it can be a string. Fewer conversions
Benchmark of parser now faster! See screenshots of PR
=> Remove some usages of bytes

src/res_diagnostics.ml, tests/parsing/errors/scanner/__snapshots__/parse.spec.js.snap
- Some folks might think it's for string concatenation.
- "hmm" might be a bit too cute.
- We should leave 2 spaces in front of a message's new lines, since our error report system is indented 2 spaces. Technically we should be using a formatter for this but whatever.
=> Fix the ^ syntax error message

src/res_core.ml, src/res_parser.ml, src/res_scanner.ml, src/res_scanner.mli, tests/res_test.ml
This actually slows this down for a tiiiny bit because of the extra
addition in `next` and `peek`... but not significant regression
=> Remove scanner rdOffset

src/res_parser.ml, src/res_parser.mli, src/res_scanner.ml, src/res_scanner.mli, tests/res_test.ml
Apparently this was needed by @ryyppy for the doc site's snippets diagnostics a while ago. Not sure it's still used. Removing it.
=> Remove parser's line seeding api

src/reactjs_jsx_ppx_v3.ml, src/res_ast_conversion.ml, src/res_core.ml, src/res_printer.ml, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/jsObject.rei, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/structure/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/typedefinition/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/typexpr/__snapshots__/parse.spec.js.snap, tests/printer/typexpr/__snapshots__/render.spec.js.snap
Fixes #277
Fixes #263
Now that https://github.com/rescript-lang/rescript-compiler/pull/4967 has landed:
- Parse `{"foo": int}` as ocaml `{. foo: int}`. Previously it parsed into ocaml `{. foo: int} Js.t`
- Remove a tiny printing optimizations for `Js.t`.
- For React's PPX 3, generate objects directly instead of `Js.t` objects. cc @rickyvetter @ryyppy for ppx4.
- The re->res converter automatically removes the `Js.t` part.
- Said converter has a bug (#263) that converts `Js.t({..}) as 'a` into `{..} as 'a` from naturally forgetting to special-case that path. Now this bug is conveniently ~~made into a feature~~ obsolete.
=> Clean up Js.t object parsing, printing and converting

.depend, src/res_ast_conversion.ml, src/res_printer.ml, src/res_printer.mli, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/attributes.re, tests/printer/structure/__snapshots__/render.spec.js.snap, tests/printer/structure/include.js
=> Clean up the conversion of @bs.* and %bs.*

src/res_parser.ml, test.res
No perf difference (we don't bench the error path)
=> Small parser cleanup

src/res_core.ml, src/res_grammar.ml, tests/printer/other/__snapshots__/render.spec.js.snap, tests/printer/other/attributes.res, tests/printer/structure/__snapshots__/render.spec.js.snap, tests/printer/structure/extension.js
Fixes https://github.com/rescript-lang/syntax/issues/260
Structure items inside an attribute payload don't need semicolons
=> Fix parsing and printing of externals inside ext/attr payload

src/res_scanner.ml, tests/parsing/errors/scanner/__snapshots__/parse.spec.js.snap
It previously didn't include the `/*` in the highlight
=> Fix eof unclosed multiline comment location report

Makefile, README.md, src/res_cli.ml
This makes the perf slightly slower (but basically unnoticeable), and the compilation slower, but this repo's files are compiled with stack trace enabled inside the compiler project anyway, so this is more realistic.
On the other hand, having a general try catch in res_cli that swallowed important exceptions such as `String.sub` and `Array.get` would have made debugging much harder.
=> Enable stack trace for binary; remove an `exit 1`

src/res_doc.ml
Optimize concat to minimize allocations.
- join text docs early
- remove Nil
- flatten nested concats
- don't allocate unless the resulting list is not the same as the incoming one.
=> Printer test: optimize concat.

src/res_driver.ml, src/res_driver_reason_binary.ml, src/res_io.ml, src/res_io.mli, tests/runner.js
#288
Though IO overhead was added for tests, I think it's negligible.
Besides, this also fixes an issue that roundtrip-test always hangs on my local machine.
I'm not sure what causes jest to run indefinitely, but now it's gone.
(before - neverending)
(after)
=> Remove res_io.readStdin

tests/res_test.ml
Before, some errors during the snapshot test would be swallowed. That was confusing.
See PR for screenshots.
=> Better outcome printer testing error message

src/res_core.ml, src/res_token.ml, tests/parsing/errors/structure/__snapshots__/parse.spec.js.snap, tests/parsing/errors/structure/letBindingPatternKeyword.js, tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typeDef/typeParams.js
"to" is a commonly use identifier in interop scenarios. to/downto take a lot of expensive grammar real estate at a very high price. Since this is a handrolled parser, we can drop them as a keyword and parse them straight as identifier.
=> Remove "to" and "downto" as keywords.

src/res_doc.ml
Instead of returning a copy of the doc with some `IfBreak`s resolved, make doc mutable to mark when an `IfBreak` has been resolved to the first branch.
This makes the function allocation-free, but with side effects on the doc.
=> Printer: make propagateForcedBreaks allocation-free.

src/res_core.ml, tests/parsing/recovery/pattern/__snapshots__/parse.spec.js.snap, tests/parsing/recovery/pattern/polyvariant.js, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/polyvariant.js, tests/printer/pattern/__snapshots__/render.spec.js.snap, tests/printer/pattern/variant.res
`#a()` and `#a(())` should be parsed as the same ast node.
Previously the former would result into a tuple of size 0.
Fixes https://github.com/rescript-lang/syntax/issues/331
=> Parse poly variant pattern with one unit arg correct.

src/res_core.ml, src/res_grammar.ml, src/res_printer.ml, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/expected/object.ml.txt, tests/conversion/reason/object.ml, tests/parsing/errors/other/__snapshots__/parse.spec.js.snap, tests/parsing/errors/other/expected/spread.res.txt, tests/parsing/errors/other/spread.res, tests/parsing/errors/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/errors/typexpr/expected/objectSpread.res.txt, tests/parsing/errors/typexpr/objectSpread.res, tests/parsing/grammar/typexpr/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/typexpr/expected/objectTypeSpreading.res.txt, tests/parsing/grammar/typexpr/objectTypeSpreading.res, tests/printer/typexpr/__snapshots__/render.spec.js.snap, tests/printer/typexpr/expected/objectTypeSpreading.res.txt, tests/printer/typexpr/objectTypeSpreading.res
Fixes https://github.com/rescript-lang/syntax/issues/278
```rescript
type a = {"x": int}
type u = {...a, "y": int}
```
=> Add support for object type spreading

src/res_ast_conversion.ml, src/res_core.ml, src/res_printer.ml, tests/conversion/reason/__snapshots__/render.spec.js.snap, tests/conversion/reason/expected/jsObject.re.txt, tests/conversion/reason/jsObject.re, tests/parsing/errors/other/__snapshots__/parse.spec.js.snap, tests/parsing/errors/other/expected/breadcrumbs170.res.txt, tests/parsing/grammar/expressions/__snapshots__/parse.spec.js.snap, tests/parsing/grammar/expressions/expected/jsx.res.txt, tests/parsing/grammar/expressions/expected/primary.res.txt
Fixes https://github.com/rescript-lang/syntax/issues/311
`obj["say"]` was currently parsed as `obj##say` (Pexp_apply with ##)
We now parse this straight into `obj#say`(Pexp_send)
=> Update object method parsing and printer for ReScript 9

.depend, src/res_outcome_printer.mli
This particular APIs are needed to be able to print typedtree data
in the playground bundle. We need that to show type hint tooltips.
=> Expose Res_outcome_printer.printOutTypeDoc / printOutSigItemDoc

test.sh
Those variables aren't block scoped. So we have to use a function and declare them with `local` scope
=> Fix test shell script

src/res_outcome_printer.ml, tests/oprint/oprint.res, tests/oprint/oprint.res.snapshot
Adds extra tests + fix minor formatting issues.
=> Tweak outcome printer for object type.

src/res_core.ml, tests/printer/expr/__snapshots__/render.spec.js.snap, tests/printer/expr/expected/ternary.res.txt, tests/printer/expr/ternary.res
Arrow functions in the "ternary true branch" where picked up as nested arrows:
`x ? y => () : onChange` for the parser was `x ? y => (() : onChange => …)`
The fix is to pass the right context through.
Fixes https://github.com/rescript-lang/syntax/issues/363
=> Fix parsing of arrow expressions in ternaries.

src/res_core.ml, tests/printer/comments/__snapshots__/render.spec.js.snap, tests/printer/comments/expected/typeDefinition.res.txt
Fixes https://github.com/rescript-lang/syntax/issues/362
The wrong end location was parsed for the `Rgb` constructor in:
```rescript
type color = /* before constr */ Rgb/*after constructor */( /* before red */ red, green, blue)
```
resulting in the comment `/* after constructor */` being moved inside the arguments
=> Fix printing of trailing comments on variant constructor without bar.

src/res_core.ml, src/res_outcome_printer.ml, src/res_printer.ml, tests/oprint/oprint.res, tests/oprint/oprint.res.snapshot, tests/parsing/grammar/expressions/expected/polyvariant.res.txt, tests/parsing/grammar/expressions/polyvariant.res, tests/parsing/grammar/pattern/expected/variants.res.txt, tests/parsing/grammar/pattern/variants.res, tests/parsing/grammar/typexpr/expected/polyVariant.res.txt, tests/parsing/grammar/typexpr/polyVariant.res, tests/printer/expr/expected/polyvariant.res.txt, tests/printer/expr/polyvariant.res, tests/printer/pattern/expected/variant.res.txt, tests/printer/pattern/variant.res, tests/printer/typexpr/expected/variant.res.txt, tests/printer/typexpr/variant.res
Extends the grammar of poly variants with integers.
```rescript
let one = #1
switch numericPolyVar {
| #89 => ()
}
type permissions = [
| #777
| #644
]
```
=> Numeric poly variant support

src/res_parsetree_viewer.ml, tests/printer/expr/binary.res, tests/printer/expr/expected/binary.res.txt
The following snippet:
```
<Kbd keycap="Ctrl" /> + <Kbd keycap="Shift" /> + <Kbd keycap />
```
would print in the non-sugared JSX form.
Nested binary expressions should print JSX correctly.
Fixes https://github.com/rescript-lang/syntax/issues/373
=> Fix printing of JSX in binary expressions.

src/res_comments_table.ml, src/res_printer.ml, tests/printer/comments/expected/pattern.res.txt, tests/printer/comments/pattern.res
Fixes https://github.com/rescript-lang/syntax/issues/374
These comments should print correct:
```rescript
switch a {
| Constr /* after constr */
| Constr /* after constr */ (a, _) => a
}
```
=> Fix printing of trailing comments on constructor part of Ppat_construct.

src/res_outcome_printer.ml
=> not display external garbage

.github/workflows/ci.yml
We have a single dependency that's faster to install than to cache lol
Also, use npm ci, which is a subset of npm install that only reads into
the lockfile and doesn't do any user-facing adjustments.
=> No need to cache npm installs anymore + use npm ci

src/res_scanner.ml, tests/parsing/grammar/expressions/es6template.res, tests/parsing/grammar/expressions/expected/es6template.res.txt
The scanner underwent extensive refactoring, it appears that something fishy was introduced in d20c137d
Upon encountering a `$` character, the routine that scans template literal tokens, shouldn't consume two characters.
Example:
```rescript
`$${dollarAmountInt}`
```
Seeing a `$` doens't imply that the next character (here also a `$`) should be consumed.
=> Fix regression in template literal string scanning.

tests/conversion/reason/attributes.re, tests/conversion/reason/expected/attributes.re.txt
Adds an extra test case that verifies https://github.com/rescript-lang/syntax/issues/399.
=> Add extra test case for conversion of bs.send.pipe from Reason

src/res_outcome_printer.ml, tests/oprint/expected/oprint.res.txt, tests/oprint/oprint.res
Fixes https://github.com/rescript-lang/syntax/issues/398
=> Implement printing of `Otyp_module` in outcome printer.

src/res_outcome_printer.ml, tests/oprint/expected/oprint.res.txt, tests/oprint/oprint.res
Modules types don't use a `=`, it should be a `:`.
```
module Expr: {
…
}
```
=> Fix printing of Osig_module in outcome printer.

src/res_core.ml, tests/parsing/grammar/typedefinition/constructorDeclaration.res, tests/parsing/grammar/typedefinition/expected/constructorDeclaration.res.txt
Fixes https://github.com/rescript-lang/syntax/issues/409
The parser should parse `type queryDelta = Compute({"blocked_ids": unit} => unit)` without parens surrounding the object type-expr `{"blocked_ids": unit}`. The parens are optional in this case. In other places like `{"blocked_ids": unit} => unit`, this was already the case.
=> Fix parsing of arrow type with objects in constructor declaration args

src/res_core.ml, tests/parsing/errors/other/expected/hashIdent.res.txt, tests/parsing/errors/other/hashIdent.res, tests/printer/typexpr/expected/variant.res.txt, tests/printer/typexpr/variant.res
`#10s` should not be accepted as a numeric polyvariant identifier.
Fixes https://github.com/rescript-lang/syntax/issues/407
=> Don't parse Int token with suffices as hash ident for poly variants

src/res_core.ml, tests/parsing/grammar/pattern/record.res, tests/printer/expr/fun.res, tests/printer/pattern/record.res
`{path as p}` formats to `{path: p`}, which is the right syntax. The as syntax is unnecessarily confusing sugar.
=> Remove `{path as p}` record pattern sugar for `{path: p}`

CHANGELOG.md, src/res_ast_conversion.ml, src/res_core.ml, src/res_printer.ml, tests/parsing/grammar/expressions/argument.res, tests/parsing/grammar/expressions/expected/argument.res.txt, tests/printer/expr/apply.res, tests/printer/expr/expected/apply.res.txt
Since there is no syntax space for arity zero vs arity one, we parse
`fn(. ())` into
`fn(. {let __res_unit = (); __res_unit})`
when the parsetree is intended for type checking
`fn(.)` is treated as zero arity application
Fixes https://github.com/rescript-lang/syntax/issues/138
=> implement syntax for arity zero vs arity one in uncurried application

.depend, src/res_scanner.ml, tests/res_test.ml
`\r\n` should be picked up as one line break, not two.
=> Handle windows CRLF correct.

src/res_outcome_printer.ml, tests/oprint/expected/oprint.resi.txt, tests/oprint/oprint.res
Fixes https://github.com/rescript-lang/syntax/issues/445
**before**
```
(~?x: 'a, ~y: 'b) => option<'a>
```
**after**
```
(~?x: 'a, ~y: 'b) => option<'a>
```
=> Fix printing of optional labeled args in outcome arrow types.

src/res_core.ml, tests/parsing/errors/expressions/expected/letBinding.res.txt, tests/parsing/errors/expressions/letBinding.res, tests/parsing/errors/other/expected/labelledParameters.res.txt, tests/parsing/errors/other/labelledParameters.res, tests/printer/comments/pattern.res
=> Fix error reporting when parsing an lident

src/res_outcome_printer.ml, tests/oprint/expected/oprint.resi.txt, tests/oprint/oprint.res
Fixes https://github.com/rescript-lang/syntax/issues/451.
`type call =  CleanStart` should be printed as `type call = CleanStart`. Notice the correct space after `=`.
=> Fix redundant space in outcome printing of constructors.

src/res_printer.ml, tests/printer/pattern/expected/variant.res.txt, tests/printer/pattern/variant.res
Fixes  https://github.com/rescript-lang/syntax/issues/472
=> fix: prevent stripping of quotes for empty polymorphic variant

src/res_printer.ml, tests/printer/modType/expected/functor.res.txt, tests/printer/modType/functor.res
fixes 
https://github.com/rescript-lang/syntax/issues/475
https://github.com/rescript-lang/syntax/issues/467
=> fix: ignore *

src/res_core.ml, tests/parsing/grammar/expressions/expected/record.res.txt, tests/parsing/grammar/expressions/record.res
This fixes https://github.com/rescript-lang/rescript-compiler/issues/5362.
I.e.
```rescript
{A.a, b}
```
is now correctly parsed to match the AST for
```rescript
{A.a: a, b: b}
```
and not for
```rescript
{A.a: A.a, b: b}
```
=> Fix parsing punned record fields with module name

src/res_core.ml
The location of `foo["abc"]` should be the whole thing, and not only `["abc"]`
Example compilation error:
```
129 │ someObj["age"] +. 0.
~~~~~~~
This has type: int
Somewhere wanted: float
```
=> Fix location of foo["abc']

src/res_printer.ml, tests/conversion/reason/expected/bracedJsx.re.txt, tests/conversion/reason/expected/braces.re.txt, tests/printer/expr/expected/block.res.txt, tests/printer/expr/expected/record.res.txt, tests/printer/expr/record.res
Currently, the printer removes record field punning as discussed in #252 (for record expressions) and #47 (for record type declarations). I.e., it expands `{a, b}` to `{a: a, b: b}`.
I gather from the discussions that we want to leave the behavior for record type declarations as it is, but improve the behavior for record expressions. This PR addresses that.
To avoid breaking changes for now, the printer will keep record expressions as the user wrote them, whether punned or not. That is, `{a, b}` will remain `{a, b}` and `{a: a, b: b}` will remain `{a: a, b: b}`.
=> Print punned fields

src/res_core.ml
More fine grained error recovery from parsing longidents.
E.g. Foo. gives Foo._ instead of a default expression which erases info on what's parser already.
From: https://github.com/rescript-lang/rescript-vscode/pull/388
=> Recovery when encountering errors parsing long idents.

src/reactjs_jsx_ppx_v3.ml, tests/ppx/react/expected/newtype.res.txt, tests/ppx/react/expected/typeConstraint.res.txt, tests/ppx/react/newtype.res, tests/ppx/react/typeConstraint.res
This reverts commit fab78d4bb48780d4a478037dbf69c3954df75b7e.
See https://github.com/rescript-lang/syntax/pull/487#discussion_r867451571
=> Revert "jsx: allow locally abstract types and type constraints on @react.component definitions (#487)"

src/reactjs_jsx_ppx_v3.ml, tests/ppx/react/expected/newtype.res.txt, tests/ppx/react/expected/typeConstraint.res.txt, tests/ppx/react/newtype.res, tests/ppx/react/typeConstraint.res
This is a continuation of #487 that fixes the type annotations for locally abstract types. Because locally abstract types can't be defined in type annotations, they have to be replaced with plain type variables, and this has to be done recursively since they can occur anywhere in a type.
The only limitation I have intentionally imposed here is that extensions are not allowed in type annotations when locally abstract types are used, because that would require traversal of the entire AST, which is no fun.
As requested, here's a complete example:
```js
module type Show = {
type t
let show: t => string
}
module Int = {
type t = int
let show = string_of_int
}
module Thing = {
@react.component
let make = (type a, ~model as module(Model: Show with type t = a), ~value: a) =>
<div> …
```
=> jsx: allow locally abstract types and type constraints on @react.component

src/res_core.ml
See https://github.com/rescript-lang/rescript-vscode/issues/416 for examples where parser recovery goes wrong in template expressions.
Basically, if the token after "." is consumed in recovery, the entire template expression is eaten up and never recovers.
This PR changes error recovery to not consume the token after Dot so the parser can recover properly inside a template.
=> More robust parse recovery after ".".

package-lock.json
Node v16 comes with npm 8 that is based on the new v2 lockfile format.
=> Update package-lock to new v2 lockfile format

.github/workflows/ci.yml, package-lock.json
I also regenerated the package-lock.json from scratch, as the previously upgraded one was broken (it caused the reanalyze binary not to be installed).
=> Use node 16 for CI build

src/res_parens.ml, src/res_parsetree_viewer.ml, src/res_printer.ml, tests/conversion/reason/expected/fastPipe.res.txt, tests/printer/expr/binary.res, tests/printer/expr/expected/binary.res.txt
Parens should be printed:
```rescript
(@doesNotRaise [])->Belt.Array.getExn(0)
```
Fixes https://github.com/rescript-lang/syntax/issues/499
=> Fix printing of parens in binary expressions with attributes

src/res_core.ml, tests/printer/expr/expected/switch.res.txt, tests/printer/expr/switch.res
I forgot to check for the mode which broke the roundtrip test for the added test case.
=> Fix problem with string in braces introduced in #494

cli/reactjs_jsx_ppx_v3.ml
Location of ReasonReact.fragment should be ghost.
See: https://github.com/rescript-lang/syntax/issues/519
https://github.com/rescript-lang/rescript-vscode/pull/449
=> Fragment ghost

.gitignore, lib/README.md, scripts/bootstrap.sh
Currently there is a `lib` dir in the repo containing only a `README.md` saying
> We store a few dev-time binaries here.
In the pre-dune setup, the `lib` dir was actually used to store `rescript.exe` etc. Now the only place it is still used is by `scripts/bootstrap.sh`. Also, invoking `scripts/bootstrap.sh` produces an uncommitted change.
I have therefore removed the `lib` dir / its README and changed the bootstrap script to use a new, git-ignored dir `bootstrap` that it creates on demand.
=> Cleanup: get rid of lib dir

benchmarks/dune, cli/dune, src/dune, tests/dune
This reverts commit d28656e2efd7270c3323e223b36acd40d5a3ed29.
Standard warnings are already defined globally in https://github.com/rescript-lang/syntax/blob/master/dune.
=> Revert "Turn on standard warnings in dune config."

tests/printer/expr/expected/templateLiteral.res.txt, tests/printer/expr/templateLiteral.res
with regard to #429, the bug in `res_printer` has been addressed at some point I guess?
=> Add tests for template literal with backslashes

src/res_core.ml, src/res_parser.ml, src/res_parser.mli, tests/parsing/infiniteLoops/expected/templateEof.res.txt, tests/parsing/infiniteLoops/templateEof.res
Parsing past Eof can lead to infinite loops, as it violates the assumptions of the termination checker.
See: https://github.com/rescript-lang/syntax/pull/540
This PR makes `Parser.next` assert false when called on Eof. This should not happen as one should check the token before calling `Parser.next`.
The one exception is during lookahead, for which we provide a `nextUnsafe` function which does not make progress.
=> Do not parse past Eof

src/res_printer.ml, tests/conversion/reason/expected/bracedJsx.res.txt, tests/conversion/reason/expected/braces.res.txt, tests/printer/expr/expected/record.res.txt, tests/printer/expr/record.res
In #480, I already prevented the printer from expanding `{a, b} to {a: a, b: b}`.
At the time, I refrained from making it collapse `{a: a, b: b}` to `{a, b}` like it used to be the case in Reason.
But I think it would actually be the better behavior to always print record fields as punned when possible.
Now that the next release is going to be a major version (10.0), it would IMHO be fine to make that change.
=> Printer: auto-pun record fields

Makefile, scripts/testok.sh
Now running reanalyze only after the normal tests.
Since introducing the exit code, the dev experience has been too strict, where even introducing an unused variable would prevent tests from running.
This also prints all tests passed at the end.
=> Reanalyze failure should not prevent running tests.

src/res_printer.ml, tests/conversion/reason/expected/jsxProps.res.txt, tests/printer/expr/expected/callback.res.txt, tests/printer/expr/expected/exoticIdent.res.txt, tests/printer/expr/expected/jsx.res.txt, tests/printer/expr/jsx.res, tests/printer/other/expected/fatSlider.res.txt, tests/printer/pattern/expected/constant.res.txt
Closes #570 
This is my first lines of code in OCaml, so I’m not sure I’m doing it right :smiley_cat:
=> Put each jsx tag on own line

.github/workflows/ci.yml, Makefile, scripts/test.sh
* Do not override default OPAM repo for Windows anymore. This fixes the Windows build.
* Beautify and format ci.yml to bring it in line with the rescript-compiler repo.
=> Fix Windows build and beautify + format ci.yml

src/res_core.ml, src/res_printer.ml, tests/parsing/grammar/expressions/expected/record.res.txt, tests/parsing/grammar/expressions/record.res, tests/printer/expr/expected/record.res.txt, tests/printer/expr/record.res
Add examples of expression and patterns showing where they are dropped.
Support all the cases discussed in https://github.com/rescript-lang/syntax/issues/583
=> Dropped annotations from punned record labels.

src/res_printer.ml, tests/printer/expr/expected/nestedCallbacks.res.txt, tests/printer/expr/nestedCallbacks.res
Stop it after a nested threshold.
This has identical output on tests, and solved the perf issue.
=> Quick fix to exponential blowup.

src/res_comment.ml, src/res_comment.mli, src/res_core.ml, src/res_parser.ml, src/res_printer.ml, src/res_scanner.ml, src/res_token.ml, tests/parsing/other/docComments.res, tests/parsing/other/expected/docComments.res.txt, tests/printer/comments/docComments.res, tests/printer/comments/expected/docComments.res.txt
Module level doc comments are of the form:
```/*** stuff */```
or internally
```@@ns.doc(" stuff ")```
=> Add support for module level doc comments.

src/res_core.ml, src/res_scanner.ml, src/res_token.ml, tests/parsing/errors/structure/expected/gh16B.res.txt, tests/parsing/grammar/expressions/expected/es6template.res.txt
See https://github.com/rescript-lang/rescript-vscode/pull/483
=> Fix location of template expressions.

src/res_printer.ml, tests/printer/comments/expected/expr.res.txt, tests/printer/comments/expr.res
This PR fixes c1 and c2 in the test disappearing. (c3 and c4 print the same as they would have before, had they been in the test.)
I was looking into this some time ago and did not submit the PR as I wasn't happy with the locations where the comments are printed. But I think for now it is good enough that they don't disappear anymore, the location can be improved separately.
=> Fix comments after function parameters disappearing

CHANGELOG.md, src/res_core.ml, src/res_grammar.ml, src/res_parens.ml, src/res_parens.mli, src/res_parsetree_viewer.ml, src/res_parsetree_viewer.mli, src/res_printer.ml, src/res_token.ml, test.res, tests/parsing/grammar/expressions/async.res, tests/parsing/grammar/expressions/await.res, tests/parsing/grammar/expressions/expected/async.res.txt, tests/parsing/grammar/expressions/expected/await.res.txt, tests/printer/expr/asyncAwait.res, tests/printer/expr/expected/asyncAwait.res.txt
Async/await surface syntax cf. https://forum.rescript-lang.org/t/ann-async-await-is-coming-to-rescript/3488
* `async` is a "non-keyword" for backwards compatibility.
* `await` has been implemented as normal keyword. Turned out to be too difficult to move forward otherwise: https://github.com/rescript-lang/syntax/pull/600#issuecomment-1175832866
=> Done, but do not merge yet: Async/Await syntax.

src/res_core.ml, tests/parsing/errors/typeDef/expected/typeDef.res.txt, tests/parsing/errors/typeDef/typeDef.res
I added error handling for the case where the last of Longident is not Lident.
I think this pr can solve part of #122 
If anyone has a better opinion, please suggest. I'll work on it.
=> improve error message of parseValuePath

cli/reactjs_jsx_ppx.ml
The [current rescript-react docs on forwarding refs](https://rescript-lang.org/docs/react/latest/forwarding-refs) discourages the use of `forwardRef` in favor of explicitly passing props. It seems a bit inconsistent then for the PPX to only recommend the `forwardRef` API then, if it should be mentioned at all. FOr now I've opted for mentioning both without encouraging one over the other.
The docs themselves could also be improved in a couple of ways:
1. It doesn't mention that the forwarded prop cannot be named `ref`, which along with this error message confused me quite a bit.
2. It's not clear how to specify the type of the component in an interface file when using `forwardRef`.
=> jsx: improve ref prop error message

CHANGELOG.md, src/res_outcome_printer.ml, tests/oprint/expected/oprint.resi.txt
https://github.com/rescript-lang/rescript-compiler/issues/5654
=> Fix printing of optional fiels in records

CHANGELOG.md, cli/reactjs_jsx_ppx.ml, tests/ppx/react/expected/commentAtTop.res.txt, tests/ppx/react/expected/fileLevelConfig.res.txt, tests/ppx/react/expected/forwardRef.res.txt, tests/ppx/react/expected/newtype.res.txt, tests/ppx/react/expected/topLevel.res.txt, tests/ppx/react/expected/typeConstraint.res.txt, tests/ppx/react/expected/v4.res.txt
This PR fixes the issue https://github.com/rescript-lang/rescript-compiler/issues/5635
It show the error with loc now.
=> Add loc for returned component body

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/externalWithRef.res.txt, tests/ppx/react/expected/externalWithTypeVariables.res.txt, tests/ppx/react/expected/forwardRef.res.txt, tests/ppx/react/expected/interfaceWithRef.res.txt, tests/ppx/react/expected/interfaceWithRef.resi.txt, tests/ppx/react/externalWithRef.res, tests/ppx/react/externalWithTypeVariables.res, tests/ppx/react/forwardRef.res, tests/ppx/react/interfaceWithRef.res, tests/ppx/react/interfaceWithRef.resi
This PR has two purposes. 
Fix the issue https://forum.rescript-lang.org/t/call-for-help-test-the-react-jsx-v4/3713/57?u=moondaddi, which is how to handle type variables for making props type.
```rescript
type t<'a>
// original
external make: (~ref: t<'a>) => React.element = "..."
// converted to
// before
type props = {ref: t<'a>} // Unbound type parameter 'a
external make: React.componentLike<props, React.element> = "..."
// after
type props<'ref> = {ref: 'ref}
external make: React.componentLike<props<t<'a>>, React.element> = "..."
}
```
The above issue reminds me that the constraint of type ref. The type constraint `ReactDOM.Ref.currentDomRef` is not flexible in case the JSX ppx is used with other jsx libraries, such as React Native. The type of ref would be different in each library. …
=> More generalized props type for ref and type variables

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/interface.res.txt, tests/ppx/react/expected/interface.resi.txt, tests/ppx/react/expected/noPropsWithKey.res.txt, tests/ppx/react/expected/removedKeyProp.res.txt, tests/ppx/react/interface.res, tests/ppx/react/interface.resi, tests/ppx/react/noPropsWithKey.res
This PR is related to https://github.com/rescript-lang/syntax/pull/640#issuecomment-1250348536
The issue is the props type is not matched in case of empty props.
```rescript
module A = {
type props = {}
}
React.createElement(A.make, Jsx.addKeyProp({}: A.props<_>, "k")) // Error
// The type A.props is not generic so expects no arguments,
// but is here applied to 1 argument(s)
```
The solution is using `React.createElementWithKey` instead of `Jsx.addKeyProp`.
1. Add `React.createElementWithKey` https://github.com/rescript-lang/rescript-react/pull/49/commits/a4c31f83d05660dc27eb2d09d6985f31373af67b
2. Add type constraint of return type for `Jsx.addKeyProp` https://github.com/rescript-lang/rescript-compiler/pull/5670
3. Use 1 and 2 in the JSX ppx
=> Fix type error by `Jsx.addKeyProp` for the empty props

CHANGELOG.md, src/res_doc.ml, src/res_doc.mli, src/res_printer.ml, tests/printer/comments/docComments.res, tests/printer/comments/expected/docComments.res.txt
https://github.com/rescript-lang/syntax/issues/639
=> Fix printing doc comments before attributes

src/res_driver.ml, src/res_driver.mli
This adds an API for parsing impl/interface from a raw string. Main use case right now is in https://github.com/rescript-lang/rescript-vscode/pull/547 where I need to parse a raw string and don't want to have to put the contents into a temp file just to parse it.
Tried adding it to `parseEngine` first but that required me to add implementations for re/ml, which felt unecessary.
=> add API for parsing impl/interface from a raw string

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/spreadProps.res.txt, tests/ppx/react/spreadProps.res
```rescript
// original
let c1 = <A {...p} />
// converted to
// v4 classic
let c1 = React.createElement(A.make, p)
// v4 automatic
let c1 = React.jsx(A.make, p)
```
=> Fix the usage of spreadProps without any other props

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/fileLevelConfig.res.txt, tests/ppx/react/expected/forwardRef.res.txt, tests/ppx/react/expected/newtype.res.txt, tests/ppx/react/expected/noPropsWithKey.res.txt, tests/ppx/react/expected/removedKeyProp.res.txt, tests/ppx/react/expected/topLevel.res.txt, tests/ppx/react/expected/typeConstraint.res.txt
I totally forgot this. This PR removed old reason related React module usages, e.g. `ReactDOMRe`, ReasonReact.fragment`
I'll add new bindings into `React.res` and `ReactDOM.res` in the rescript-react
=> Remove the reason related module usage

CHANGELOG.md, cli/JSXV4.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/commentAtTop.res.txt, tests/ppx/react/expected/externalWithCustomName.res.txt, tests/ppx/react/expected/externalWithRef.res.txt, tests/ppx/react/expected/externalWithTypeVariables.res.txt, tests/ppx/react/expected/fileLevelConfig.res.txt, tests/ppx/react/expected/interface.res.txt, tests/ppx/react/expected/interface.resi.txt, tests/ppx/react/expected/interfaceWithRef.res.txt, tests/ppx/react/expected/interfaceWithRef.resi.txt, tests/ppx/react/expected/newtype.res.txt, tests/ppx/react/expected/removedKeyProp.res.txt, tests/ppx/react/expected/topLevel.res.txt, tests/ppx/react/expected/typeConstraint.res.txt, tests/ppx/react/expected/v4.res.txt
Adding loc to the generated props type as pointing to the same location of `@react.component` in each str_item and sig_item.
Fixed #654
=> Better error msg and loc for multiple props type declaration

cli/JSXV4.md
about not adding `@rescript/react` into v3-deps
=> Update jsx v4 doc

CHANGELOG.md, src/res_core.ml, tests/parsing/grammar/expressions/expected/underscoreApply.res.txt, tests/parsing/grammar/expressions/underscoreApply.res, tests/printer/expr/expected/underscoreApply.res.txt, tests/printer/expr/underscoreApply.res
Fixes https://github.com/rescript-lang/syntax/issues/661
=> Fix parsing of expressions with underscore `_` and comments.

CHANGELOG.md, src/res_comments_table.ml, src/res_printer.ml, tests/conversion/reason/expected/bracedJsx.res.txt, tests/printer/comments/expected/jsx.res.txt, tests/printer/comments/jsx.res, tests/printer/expr/expected/jsx.res.txt, tests/printer/other/expected/signaturePicker.res.txt
Closes https://github.com/rescript-lang/syntax/issues/663
```res
// The minimal reproducible example
<A
a="1"
// comment
>
<B />
</A>
```
tweak the output of `jsx` tag
```res
// before
<A
// comment  
a="1"
/* comment */> 
<B />
</A>
// now
<A
// comment -- align with a="1"
a="1"
/* comment */   //  align with a="1"
>       // print > on a separate line -- same as prettier
<B />
</A>
```
=> fix: Avoid tail comments inside tag from being eaten

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/firstClassModules.res.txt, tests/ppx/react/expected/firstClassModules.resi.txt, tests/ppx/react/firstClassModules.res, tests/ppx/react/firstClassModules.resi
Feedback from forum https://forum.rescript-lang.org/t/call-for-help-2-test-jsx-v4/3781/16?u=moondaddi
This PR fixes it
=> Fix JSX v4 for first class module

CHANGELOG.md, src/res_parsetree_viewer.ml, tests/conversion/reason/expected/uncurrried.res.txt, tests/printer/expr/expected/fun.res.txt, tests/printer/expr/fun.res, tests/printer/typexpr/expected/arrow.res.txt
Arrow functions with multiple dots `(. a, . b) => a + b` are considered an anti-pattern. This syntax *will be removed* in the future. As a first step, the printer will know print this as multiple arrow functions. (Like in JavaScript)
**Before**
```rescript
let f = (. a, . b) => a + b
type f = (. int, . int) => int
```
**After**
```rescript
let f = (. a) => (. b) => a + b
type f = (. int) => (. int) => int
```
=> Remove printing of arrow functions with "multiple" dots

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/commentAtTop.res.txt, tests/ppx/react/expected/fileLevelConfig.res.txt, tests/ppx/react/expected/forwardRef.res.txt, tests/ppx/react/expected/optimizeAutomaticMode.res.txt, tests/ppx/react/optimizeAutomaticMode.res
=> Remove `Caml_option.some` from jsx mode

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/forwardRef.res.txt, tests/ppx/react/expected/lowercases.res.txt, tests/ppx/react/lowercases.res
This PR changes the internal representation of JSX v4 lowercase e.g. `<div />` from object to record
=> JSX v4 record-based representation for lowercase

CHANGELOG.md, cli/reactjs_jsx_v4.ml
Fixes https://github.com/rescript-lang/rescript-compiler/issues/5724
=> Emit an error when a @string or @int attribute is used in V4.

CHANGELOG.md, src/res_core.ml, tests/parsing/errors/other/expected/spread.res.txt
The current behavior is: if the last list element expression is a [spread](https://rescript-lang.org/docs/manual/latest/array-and-list#immutable-prepend), the parser will not check the rest element whether contains a spread expression. 
This PR adds a spread element check when the last list element is a spread.
Please see #670 for more details.
=> Add spread element check when the last element is a spread. 

CHANGELOG.md, src/res_parsetree_viewer.ml, src/res_printer.ml, tests/printer/expr/asyncAwait.res, tests/printer/expr/expected/asyncAwait.res.txt, tests/printer/expr/expected/fun.res.txt
See https://github.com/rescript-lang/syntax/issues/679
=> Fix several printing issues with `async` including an infinite loop.

src/res_printer.ml, tests/conversion/reason/expected/bracedJsx.res.txt, tests/printer/comments/expected/jsx.res.txt, tests/printer/comments/jsx.res, tests/printer/expr/expected/jsx.res.txt, tests/printer/other/expected/signaturePicker.res.txt
Closes https://github.com/rescript-lang/syntax/issues/675
=> fix: do not print > on new line

src/res_printer.ml, tests/printer/comments/expected/jsx.res.txt
Closes https://github.com/rescript-lang/syntax/issues/675 again...
See https://github.com/rescript-lang/syntax/issues/675#issuecomment-1279882340
=> fix: put > on a new line if the tag or last prop has trailing comments

CHANGELOG.md, src/res_printer.ml, tests/printer/expr/asyncAwait.res, tests/printer/expr/expected/asyncAwait.res.txt
Fixes https://github.com/rescript-lang/syntax/issues/687
Certain nested patterns for binary operators are printed "manually" so the special printing for await is not used.
=> Fix issue where printing nested pipe discards await

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/noPropsWithKey.res.txt, tests/ppx/react/expected/optionalKeyType.res.txt, tests/ppx/react/expected/spreadProps.res.txt
This PR corresponds to the changes rescript-react binding https://github.com/rescript-lang/rescript-react/pull/74/commits/234798b97ecf6b1a979196c97f46a36d97361289 to make cleaner js output.
=> Change calling jsxKeyed bindings

cli/react_jsx_common.ml, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/sharedProps.res.txt, tests/ppx/react/expected/sharedProps.resi.txt, tests/ppx/react/sharedProps.res, tests/ppx/react/sharedProps.resi
This PR adds a new feature for JSX v4 which is using shared props type as an argument of `@react.component`
https://github.com/rescript-lang/syntax/issues/695
Example
```rescript
type sharedProps<'a> = {x: 'a, y: string}
// original
module V4C2 = {
@react.component(:sharedProps<'a>) // <- here
let make = (~x, ~y) => React.string(x ++ y)
}
// converted to
module V4C2 = {
type props<'a> = sharedProps<'a>
@react.component(: sharedProps<'a>) let make = ({x, y, _}: props<'a>) => React.string(x ++ y)
let make = {
let \"SharedProps$V4C2" = (props: props<_>) => make(props)
\"SharedProps$V4C2"
}
}
```
=> JSX v4 shared props

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/sharedProps.res.txt, tests/ppx/react/expected/sharedProps.resi.txt
This PR fixes https://github.com/rescript-lang/syntax/pull/701#issuecomment-1293149369
=> Fix props type constraint for shared props

cli/JSXV4.md
This PR updates the JSX v4 spec about sharing props type regarding the PR #699
=> Update v4 spec about sharing props type

cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/noPropsWithKey.res.txt, tests/ppx/react/expected/optionalKeyType.res.txt, tests/ppx/react/expected/removedKeyProp.res.txt
This PR makes JSX v4 calls `ReactPPX4Support` helper functions from the compiler.
https://github.com/rescript-lang/rescript-react/issues/76
=> Use JsxPPXReactSupport module from compiler

CHANGELOG.md, src/res_core.ml, src/res_parens.ml, src/res_parens.mli, src/res_printer.ml, tests/parsing/grammar/expressions/async.res, tests/parsing/grammar/expressions/expected/async.res.txt, tests/printer/expr/asyncAwait.res, tests/printer/expr/expected/asyncAwait.res.txt
Making pipe behave just like application seems pretty unlikely. First `->` has deep binary operator behavior, including associating to the left on `a->b->c`, and mixes in specific ways with other operators. Instead application lives on a different level entirely with no issues of how to treat specially the right-hand-side which is enclosed in parens (and lives in a radically different place in the call stack of the parser).
The await operator is essentially a unary operator. After all it takes one argument. It is also treated as such in JS. Some expected behaviours are that `await 2 + await 3` just like `-2 + -3` is expected to mean `(await 2) + (await 3)`. Or: `await getName() ++ await getSurname()`.
The issue raised by people who have tried `await` is in combination with pipe: the …
=> Treat await as an almost-unary operator.

cli/JSXV4.md
This PR fixes the v3 compatible mode configuration example.
=> Fix JSX v4 spec about configuration

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/aliasProps.res, tests/ppx/react/expected/aliasProps.res.txt
This PR fixes https://github.com/rescript-lang/rescript-compiler/issues/5880
=> Fix build error where aliasing argument to `_` in make function with jsx v4

CHANGELOG.md, src/res_core.ml, src/res_parsetree_viewer.ml, src/res_printer.ml, tests/parsing/grammar/expressions/expected/arrow.res.txt, tests/ppx/react/expected/fileLevelConfig.res.txt, tests/ppx/react/expected/forwardRef.res.txt, tests/ppx/react/expected/innerModule.res.txt, tests/ppx/react/expected/topLevel.res.txt, tests/printer/expr/asyncAwait.res, tests/printer/expr/expected/asyncAwait.res.txt
This PR revives the closed PR https://github.com/rescript-lang/syntax/pull/683 It also makes sync to the compiler. https://github.com/rescript-lang/rescript-compiler/pull/5783
=> Simplify parsing attributes of function and args

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/mangleKeyword.res.txt, tests/ppx/react/mangleKeyword.res
This PR is to backport https://github.com/rescript-lang/rescript-compiler/pull/5905
=> Fix dropping attributes of props in JSX v4

README.md
Add deprecation notice to point people to the compiler repo.
How shall we handle the existing issues and PRs BTW?
=> Deprecate syntax repo

cli/reactjs_jsx_ppx.ml
When setting the JSX mode in-source via
```rescript
@@jsxConfig({version: 4, mode: "automatic"})
````
it is currently ignored. This is because the AST is
```
Pexp_constant PConst_string ("automatic",Some "js")
```
but the code was matching for
```ocaml
{pexp_desc = Pexp_constant (Pconst_string (value, None))}
```
=> Fix jsx mode being ignored when set via @@jsxConfig

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/forwardRef.res.txt
Backporting https://github.com/rescript-lang/rescript-compiler/pull/5960
=> Add the missing loc of jsx call expression

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/uncurriedProps.res.txt, tests/ppx/react/uncurriedProps.res
This PR fixes the issue https://github.com/rescript-lang/rescript-compiler/issues/5969
This change keeps the attributes of the argument in the make function and removes the unnecessary optional attr from the core_type as the type parameter. So it prevents that uncurried functions were incorrectly converting the type of a prop given as a default value.
The current master in the compiler transforms the uncurried type annotation correctly without this change, but this change can fix the issue in v10.1.2
=> JSX4: Fix missing attributes from props type

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/v4.res.txt, tests/ppx/react/v4.res
This PR fixes the issue https://github.com/rescript-lang/rescript-compiler/issues/5981, backporting https://github.com/rescript-lang/rescript-compiler/pull/5986 to syntax
=> Fix support for recursive components in JSX4

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/aliasProps.res, tests/ppx/react/defaultValueProp.res, tests/ppx/react/expected/aliasProps.res.txt, tests/ppx/react/expected/defaultValueProp.res.txt, tests/ppx/react/expected/uncurriedProps.res.txt
This PR fixes https://github.com/rescript-lang/rescript-compiler/issues/5977
=> Fix issue overlapping argument with default value and alias with default value

CHANGELOG.md, src/res_comments_table.ml, src/res_printer.ml, tests/printer/expr/expected/switch.res.txt, tests/printer/expr/switch.res
Backporting https://github.com/rescript-lang/rescript-compiler/pull/6015
=> Fix formatting of `switch` expressions that contain braced cases inside

CHANGELOG.md, src/res_printer.ml, tests/printer/expr/expected/jsx.res.txt, tests/printer/expr/jsx.res
Backporting https://github.com/rescript-lang/rescript-compiler/pull/6006
=> Fix formatting of props spread for multiline JSX expression

CHANGELOG.md, cli/reactjs_jsx_v4.ml, tests/ppx/react/expected/aliasProps.res.txt, tests/ppx/react/expected/commentAtTop.res.txt, tests/ppx/react/expected/defaultValueProp.res.txt, tests/ppx/react/expected/fileLevelConfig.res.txt, tests/ppx/react/expected/firstClassModules.res.txt, tests/ppx/react/expected/forwardRef.res.txt, tests/ppx/react/expected/interface.res.txt, tests/ppx/react/expected/mangleKeyword.res.txt, tests/ppx/react/expected/newtype.res.txt, tests/ppx/react/expected/optimizeAutomaticMode.res.txt, tests/ppx/react/expected/removedKeyProp.res.txt, tests/ppx/react/expected/topLevel.res.txt, tests/ppx/react/expected/typeConstraint.res.txt, tests/ppx/react/expected/v4.res.txt, tests/ppx/react/newtype.res
This is a port of PR https://github.com/rescript-lang/rescript-compiler/pull/6029
=> Fix issue with JSX V4 and newtype
