rescript-lang/syntax

src/napkin_token.ml

Was printing `list`. It fell into Lident in my change but toString showed `list` so that was confusing

Token.toString Lident and Uident

---

src/napkin_diagnostics.ml
src/napkin_diagnostics.mli

Add functions accessing diagnostics startPos / endPos

---

.depend
Makefile
src/napkin_io.ml
src/napkin_io.mli
src/napkin_multi_printer.ml

Fixes https://github.com/BuckleScript/syntax/issues/44 by using the `Sys` module.

Remove Unix Dependency

---

src/napkin_core.ml
src/napkin_diagnostics.ml
src/napkin_grammar.ml
tests/parsing/errors/pattern/__snapshots__/parse.spec.js.snap
tests/parsing/errors/pattern/missing.res
tests/parsing/errors/pattern/parse.spec.js

Improve error messages for missing patterns

---

.depend
Makefile
tests/napkin_diff.ml
tests/napkin_diff.mli
tests/napkin_test.ml
tests/oprint/oprint.res
tests/oprint/oprint.res.snapshot

Provides diffs for the outcome printer snapshots based on https://en.wikipedia.org/wiki/Longest_common_subsequence_problem and https://en.wikipedia.org/wiki/Diff

Implement diffing algorithm for snapshot tests of outcome printer.

---

src/napkin_cli.ml

Default to printing ns (human-readable)

---

.gitignore
.vscode/ninja.js
.vscode/task.js
.vscode/tasks.json
Makefile

If you use vscode, command+shift+b to enjoy the much better development experience.
Personal suggestions, I don't rely on merlin for error reporting, this is my personal vscode settings:
.vscode/settings.json
```json
{
"ocaml.lintOnSave": false,
"ocaml.lintOnChange": false,    
}
```
Some other tweaks:
- absname for precise error location
- some tweaks for Makefile

watch mode for development

---

src/res_diagnostics.ml
src/res_diagnostics.mli

@ryyppy no longer needs it, right?

Unexpose Res_diagnostics.toString

---

src/res_doc.ml
src/res_doc.mli
src/res_printer.ml
tests/printer/expr/__snapshots__/render.spec.js.snap
tests/printer/expr/callback.js

Fixes https://github.com/rescript-lang/syntax/issues/166
Fixes https://github.com/rescript-lang/syntax/issues/111

Callback improvements

---

src/res_character_codes.ml
src/res_core.ml
src/res_diagnostics.ml
src/res_diagnostics.mli
src/res_scanner.ml
src/res_scanner.mli
src/res_token.ml

- Try pattern matching on character in the scanner instead of using if-else with number constants
- Make scanner use char directly instead of converting back and forth between char and int

Clean up scanner

---

src/res_scanner.ml
tests/parsing/errors/scanner/__snapshots__/parse.spec.js.snap

This also fixes the bug of not showing the error display because the location was wrong.

Better error msg for multi-line exotic ident

---

src/res_scanner.ml

The `scan` code was rather irregular, due to some quirks around when to `peek`, when to `next`, etc. I'm guessing out of a misguided desire to save perf.
The realization is that peeking 1 or 2 chars have the same perf, likewise for `next`ing 1 or 2 chars (well, in this diff, `next`ing 2 or 3 times are slightly more expensive but that's trivially fixable). Once we see that, we can just freely throw around the right amount of `peek` and `next` without needing to share some `next` code paths with some character lookahead and not with others.
Perf is actually better now! Screenshot in PR.
Also, much more readable. Previously, every time I check the `scan` code I needed to wrangle about which char I’m looking at and which char I’m looking at next, because of various imperative `next` calls …

CLEAN UP Scanner.scan EVEN MORE

---

src/res_scanner.ml

Took the occasion to make some misc cleanups.
Better perf, better readability!

Convert most scanner logic into pattern matching

---

src/res_scanner.ml

This way things are less error prone
However... Having to check for newline every `next` regressed the perf back to the level after #269 😭... it's ok, we've earned it. There's been nothing but readability cleanup along the way so it's still a net win for reading.

Scanner: clean up newline logic

---

src/res_character_codes.ml
src/res_scanner.ml

It's unclear whether this is more readable, but whatever

Further code cleanup

---

src/res_printer.ml

Not much perf difference. Slightly faster?

Make Printer.classifyIdentContent much more readable

---

Makefile
src/res_cli.ml

See the screenshot attached to the PR for more details. And @IwanKaramazow's upcoming explanations of `forPrinter`'s role in this

Make CLI flags more rigorous

---

src/res_parens.ml
tests/conversion/reason/__snapshots__/render.spec.js.snap
tests/conversion/reason/modType.re
tests/printer/modType/__snapshots__/render.spec.js.snap
tests/printer/modType/withConstraints.js

Fixes https://github.com/rescript-lang/syntax/issues/264

Fix printing of nested Pmty_with module types.

---

tests/oprint/oprint.res
tests/oprint/oprint.res.snapshot

Add outcome printer test for erasure of Js.t

---

src/res_cli.ml

Never supported more than one it seems?

CLI: we only support parsing one file

---

src/res_ast_conversion.ml
src/res_core.ml
src/res_grammar.ml
tests/conversion/reason/__snapshots__/render.spec.js.snap
tests/conversion/reason/string.re
tests/parsing/errors/pattern/__snapshots__/parse.spec.js.snap
tests/parsing/errors/pattern/templateLiteral.res
tests/parsing/grammar/pattern/__snapshots__/parse.spec.js.snap
tests/parsing/grammar/pattern/constant.js
tests/printer/pattern/__snapshots__/render.spec.js.snap
tests/printer/pattern/constant.res

Fixes https://github.com/rescript-lang/syntax/issues/314

Add support for parsing template literals in patterns.

---

src/res_diagnostics.ml
src/res_diagnostics_printing_utils.ml
tests/parsing/errors/expressions/__snapshots__/parse.spec.js.snap
tests/parsing/errors/other/__snapshots__/parse.spec.js.snap
tests/parsing/errors/pattern/__snapshots__/parse.spec.js.snap
tests/parsing/errors/scanner/__snapshots__/parse.spec.js.snap
tests/parsing/errors/signature/__snapshots__/parse.spec.js.snap
tests/parsing/errors/structure/__snapshots__/parse.spec.js.snap
tests/parsing/errors/typeDef/__snapshots__/parse.spec.js.snap
tests/parsing/errors/typexpr/__snapshots__/parse.spec.js.snap
tests/parsing/infiniteLoops/__snapshots__/parse.spec.js.snap

All the way til https://github.com/rescript-lang/rescript-compiler/commit/0af427fcd244743d0e1cf2df0868db623f2eec1b

Sync over error report changes from compiler repo

---

test.sh

We have lots of files, can't blindly spawn a process per test file. Chunk them.

Chunk up test parallelization

---

src/res_parsetree_viewer.ml
src/res_parsetree_viewer.mli
src/res_printer.ml
tests/conversion/reason/expected/underscoreSugar.re.txt
tests/conversion/reason/underscoreSugar.re
tests/printer/expr/expected/underscoreApply.res.txt
tests/printer/expr/underscoreApply.res

fixes https://github.com/rescript-lang/syntax/issues/413

Fix printing of underscore Pexp_fun sugar in context of Array.get

---

src/res_scanner.ml

Fix issue where the parser crashes on empty unterminated comment.

---

src/res_parens.ml
src/res_parsetree_viewer.ml
src/res_parsetree_viewer.mli
src/res_printer.ml

* Spelling fix: printeable -> printable
* Avoid unnecessary List construction
* Make sure filterPrintableAttributes and partitionPrintableAttributes use the same definition of "printable"

Printable attribute improvements

---

.github/workflows/ci.yml
scripts/test.sh

Run tests on Linux

---

src/res_outcome_printer.ml
tests/oprint/expected/oprint.resi.txt

I took the existing expected test result, pasted it into the rescript playground, fixed all the errors there, then fixed the code to actually produce that result. A pretty rough process, but the fixes were all pretty simple so I hope this is accurate enough.

fix outcome printer bugs

---

.ocamlformat
.ocamlformat-ignore
Makefile
benchmarks/dune
dune-project
rescript-syntax.opam
src/res_utf8.ml

As discussed with @cristianoc, add ocamlformat to the project, but do not reformat files or enforce formatting in CI yet.

ocamlformat

---

src/res_comments_table.ml
src/res_parsetree_viewer.ml
src/res_parsetree_viewer.mli
src/res_printer.ml
tests/printer/comments/expected/expr.res.txt
tests/printer/comments/expected/ifThenElse.res.txt
tests/printer/comments/ifThenElse.res

Fix comment before Pexp_ifthenelse moving into if branch

---

src/res_comments_table.ml
src/res_printer.ml
tests/printer/comments/expected/jsx.res.txt
tests/printer/comments/jsx.res

Fix comments in JSX jumping inside braces

---

src/res_parsetree_viewer.ml
tests/printer/expr/expected/callback.res.txt
tests/printer/expr/expected/switch.res.txt
tests/printer/expr/switch.res

Fix inconsistent formatting behavior with fragments

---

.github/workflows/ci.yml
Makefile

As suggested by @cristianoc to increase the chance of discovering formatting issues during local development/testing (and not later on in CI).

Run ocamlformat check in tests

---

cli/reactjs_jsx_ppx_v4.ml
compiler-libs-406/printtyp.ml
src/res_core.ml
tests/oprint/expected/oprint.resi.txt
tests/oprint/oprint.res
tests/parsing/grammar/expressions/expected/record.res.txt
tests/parsing/grammar/expressions/record.res
tests/ppx/react/expected/commentAtTop.res_v4_auto.txt
tests/ppx/react/expected/commentAtTop.res_v4_cls.txt
tests/ppx/react/expected/externalWithCustomName.res_v4_auto.txt
tests/ppx/react/expected/externalWithCustomName.res_v4_cls.txt
tests/ppx/react/expected/forwardRef.res_v4_auto.txt
tests/ppx/react/expected/forwardRef.res_v4_cls.txt
tests/ppx/react/expected/innerModule.res_v4_auto.txt
tests/ppx/react/expected/innerModule.res_v4_cls.txt
tests/ppx/react/expected/newtype.res_v4_auto.txt
tests/ppx/react/expected/newtype.res_v4_cls.txt
tests/ppx/react/expected/topLevel.res_v4_auto.txt
tests/ppx/react/expected/topLevel.res_v4_cls.txt
tests/ppx/react/expected/typeConstraint.res_v4_auto.txt
tests/ppx/react/expected/typeConstraint.res_v4_cls.txt
tests/printer/expr/expected/record.res.txt
tests/printer/expr/record.res

Convert all the examples and the JSX ppx.

Remove `@optional` and convert to using `@ns.optional`.

---

cli/reactjs_jsx_ppx.ml
tests/ppx/react/expected/forwardRef.res.txt

* Fixed issues 9, 11 in #615
* Polished the loc wired to proper AST node.

Improve error with loc

---

src/res_core.ml
tests/parsing/grammar/expressions/expected/record.res.txt
tests/parsing/grammar/expressions/record.res
tests/printer/typeDef/expected/record.res.txt
tests/printer/typeDef/record.res

Add test. Multiple fields works fine.
See: https://github.com/rescript-lang/syntax/issues/627

Issue with single optional field with attributes.

---

cli/JSXV4.md

Update v4 doc about spread props

---

cli/JSXV4.md

Fixes https://github.com/rescript-lang/syntax/issues/653

Clarify spec of V4 JSX transformations.

---

CHANGELOG.md
src/res_core.ml
tests/ppx/react/expected/spreadProps.res.txt
tests/ppx/react/spreadProps.res

This PR fixes https://github.com/rescript-lang/rescript-compiler/issues/5882

Fix parsing not atomic expression in spread props of JSX
